export const cssSecurityList: { [key: string]: string[] } = {
  background: ['*'],
  'background-color': ['*'],
  border: ['*'],
  'border-bottom': ['*'],
  'border-bottom-color': ['*'],
  'border-bottom-style': ['*'],
  'border-bottom-width': ['*'],
  'border-color': ['*'],
  'border-left': ['*'],
  'border-left-color': ['*'],
  'border-left-style': ['*'],
  'border-left-width': ['*'],
  'border-right': ['*'],
  'border-right-color': ['*'],
  'border-right-style': ['*'],
  'border-right-width': ['*'],
  'border-style': ['*'],
  'border-top': ['*'],
  'border-top-color': ['*'],
  'border-width': ['*'],
  color: ['*'],
  display: [
    'block',
    'flex',
    'inline-block',
    'inline-flex',
    'inline',
    'inline-table',
    'list-item',
    'table',
    'table-caption',
    'table-cell',
    'table-column',
    'table-column-group',
    'table-footer-group',
    'table-header-group',
    'table-row',
    'table-row-group',
  ],
  font: ['*'],
  'font-family': ['*'],
  'font-size': ['*'],
  'font-style': ['*'],
  'font-variant': ['*'],
  'font-weight': ['*'],
  height: ['*'],
  'letter-spacing': ['*'],
  'line-height': ['*'],
  'list-style-type': ['*'],
  padding: ['*'],
  'padding-bottom': ['*'],
  'padding-left': ['*'],
  'padding-right': ['*'],
  'padding-top': ['*'],
  'table-layout': ['*'],
  'text-align': ['*'],
  'text-decoration': ['*'],
  'text-indent': ['*'],
  'text-transform': ['*'],
  'vertical-align': ['*'],
  width: ['*'],
};
