#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/runner/work/jsx-mail/jsx-mail/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/runner/work/jsx-mail/jsx-mail/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/esbuild" "$@"
else
  exec node  "$basedir/../../bin/esbuild" "$@"
fi
