name = "jsxmail-edge"
main = "src/index.ts"
compatibility_date = "2022-10-10"

[triggers]
crons = ["0 0 * * *"]

[observability]
enabled = true

[vars]
BASE_API_URL = "https://api.jsxmail.org"
DEV_BASE_API_URL = "https://dev-api.jsxmail.org"

# [secrets]
# JSXMAIL_API_TOKEN = "..."
# DEV_JSXMAIL_API_TOKEN = "..."
