name: Release
on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - '.github/workflows/release-pkg.yml'
  workflow_dispatch:

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install
      - name: build
        run: cd packages/core && pnpm run build && cd .. && cd jsx-mail && pnpm run build
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
